name: Sync Resume PDF to Website

on:
  push:
    branches:
      - master      # or whichever branch you use

jobs:
  sync-resume:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout this (Resume) repo
      - name: Checkout Resume repo
        uses: actions/checkout@v3
        with:
          repository: Sharwin24/Resume
          path: Resume

      # 2) Checkout the website repo into ./site
      - name: Checkout Website repo
        uses: actions/checkout@v3
        with:
          repository: Sharwin24/sharwin24.github.io
          token: ${{ secrets.WEBSITE_PAT }}
          path: site

      # 3) Copy the PDF into your site's static folder
      - name: Copy resume PDF into website
        run: |
          mkdir -p site/content/resume
          cp Resume/main.pdf site/content/resume/SharwinPatilResume.pdf

      # 4) Commit & push if there are changes
      - name: Commit & push changes
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add site/content/resume/SharwinPatilResume.pdf
          git diff --cached --exit-code || ( \
            git commit -m "chore: update resume PDF" && \
            git push \
          )
